[workspace]
authors = ["Erwan Demairy <Erwan.Demairy@inria.fr>"]
channels = ["conda-forge"]
preview = ["pixi-build"]
name = "igor"
platforms = ["linux-64", "osx-arm64", "osx-64", "win-64"]
version = "0.1.0"

[dependencies]
cmake = "*"
gsl = "*"
cxx-compiler = "*"
doxygen = "~=1.8"
catch2 = "3.*"
ninja = "*"
anaconda-client = "*"
sparrow-devel = "*"
arrow-cpp = "*"

[target.osx.dependencies]
clang-tools = ">=19.1.7,<22"

[target.linux.dependencies]
valgrind = "*"

[tasks]
clean = "rm -fr build && rm -fr build_cov"
configure_debug = "cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Debug"
configure = "cmake -S . -B build -G Ninja"
configure_coverage = "cmake -S . -B build_cov -DBUILD_DOC_DOXYGEN=ON -DENABLE_COVERAGE=ON  -DCMAKE_CXX_SCAN_FOR_MODULES=OFF"
build = {cmd="cmake --build build --parallel", depends-on = "configure"}
build_debug = {cmd="cmake --build build --parallel", depends-on = "configure_debug"}
build_coverage = {cmd="cmake --build build_cov -j8", depends-on = "configure_coverage"}
test = {cmd="ctest --test-dir build --output-on-failure", depends-on = "build"}
test_debug = {cmd="ctest --test-dir build --output-on-failure", depends-on = "build_debug"}
test_unit = {cmd="ctest --test-dir build --output-on-failure -L unit", depends-on = "build"}
test_unit_debug = {cmd="ctest --test-dir build --output-on-failure -L unit", depends-on = "build_debug"}
test_integration = {cmd="ctest --test-dir build --output-on-failure -L integration", depends-on = "build"}
test_integration_debug = {cmd="ctest --test-dir build --output-on-failure -L integration", depends-on = "build_debug"}
test_regression = { cmd = "scripts/tests/test_run.sh", depends-on = ["build"] }
test_align = { cmd = "scripts/tests/test_align.sh", depends-on = ["build"] }
benchmark = { cmd = "scripts/tests/benchmark_run.sh", depends-on = ["build"] }
doc = "cmake --build build --target doc"
format = "cmake --build build --target clang-format"
coverage = {cmd="llvm-profdata merge -sparse build_cov/tst/default.profraw -o default.profdata && llvm-cov show build_cov/bin/igor_tests -instr-profile=default.profdata -format=html -output-dir=htmlcov", depends-on = "build_coverage"}
submodule-update = "git submodule update --init --recursive"

[target.win-64.tasks]
configure = "cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release"

[target.linux.tasks]
memcheck = {cmd="ctest --test-dir build -T memcheck --timeout 240 -C Release --output-junit ../ctest-memcheck-junit.xml", depends-on = "build"}

[tasks.upload]
args = ["token", { arg = "label", default = "main" },{ arg = "channel", default = "nniclausse" }]
cmd = "anaconda --token {{ token }} upload --skip-existing --user {{ channel }} --label {{ label }} bundle/*.conda "

# ------------------build package (pixi build)--------------------------------

[package]
name = "igor_vdj"
version = "1.4.0"
description = "IGoR is a C++ software designed to infer V(D)J recombination related processes from sequencing data"

[workspace.target.osx.build-variants]
cxx_compiler_version = ["19.*"]

[workspace.target.linux.build-variants]
cxx_compiler_version = ["14.*"]

[workspace.target.win.build-variants]
cxx_compiler = ["vs2022"]

[package.build.backend]
name = "pixi-build-cmake"
version = "*"

[package.build.config]
extra-args = ["-DCMAKE_BUILD_TYPE=Release"]
env = { MACOSX_DEPLOYMENT_TARGET = "13.4" }


[package.build-dependencies]

[package.host-dependencies]
# Add dependencies on (header-only) libraries at compile time
gsl = "*"
catch2 = "3.*"
sparrow-devel = "*"
arrow-cpp = "*"

[package.run-dependencies]
gsl = "*"
arrow-cpp = "*"
sparrow-devel = "*"

[target.linux-64.dependencies]
valgrind = ">=3.26.0,<4"
