package:
  name: igor
  version: 1.4.0

source:
  path: ../..

build:
  number: 2
  # script: bash build.sh

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make
  host:
    - gsl
    - llvm-openmp  # [osx]
    - doxygen ~=1.8
    - catch2 3.*
#   run:
#     - gsl
#     - llvm-openmp  # [osx]

test:
  commands:
    - igor -help

about:
  home: https://gitlab.com/igor-lab/igor
  license: GPL-3.0
  summary: Inference and Generation of Repertoires
