name: CI

on:
  push:
    branches:
      - feature/1-make-software-installation-easier-for-non-technical-users
      # - master
      # - main
  pull_request:
    branches:
      - feature/1-make-software-installation-easier-for-non-technical-users
      # - master
      # - main

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.8.1
        with:
          pixi-version: v0.39.0
          cache: true
      - name: Configure
        run: pixi run configure
      - name: Build
        run: pixi run build
      - name: Test
        run: pixi run test
